// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.web;

import org.springframework.stereotype.Controller;

privileged aspect MainController_Roo_Thymeleaf_MainController {
    
    declare @type: MainController: @Controller;
    
}
